### ISSUE TITLE
Header/body compression conflict - S3/Dragonfly/HerokuRailsDeflate

### ISSUE THREAD

**Issue by zetlan** [mattolson/heroku_rails_deflate#10]
The symptom here is that certain images served from my Rails app are viewable in every browser but the latest Google Chrome (version 30). Root cause is that the image body is sent uncompressed, but the response header includes `Content-Encoding: gzip` which then fails to decompress.

The root cause is an apparent conflict between the middleware layers. My app uses Dragonfly (which uses fog) for image management, and the images users upload are stored uncompressed on Amazon S3.
- Dragonfly inserts its own middleware after Rack::Cache
- heroku_rails_deflate inserts Rack::Deflater after Rack::Cache, and then inserts HerokuRailsDeflate::ServeZippedAssets after Rack::Deflater

It appears that Dragonfly runs first & pulls the file, and Rack::Deflater runs on that, with ServeZippedAssets following. Dragonfly uses fog's AWS library to pull the file. All of this happens in the middleware layer (which is starting to get pretty thick).

So, sequence of events appears to be:
1. Browser demands a file (GET /system/XXXX/images/foo.png)
2. Dragonfly figures out where to get the file, and pulls it from Amazon S3, and makes it available via the middleware (ActionDispatch). The file is not stored Gzipped on S3, and so it isn't compressed.
3. Heroku_Rails_Deflate makes some attempt to figure out whether the file is compressed – but the test for this is to call Rack::Utils.select_best_encoding to see what Rack _would_ do (https://github.com/mattolson/heroku_rails_deflate/blob/master/lib/heroku_rails_deflate/serve_zipped_assets.rb line 17). Rack would select gzip encoding, so Heroku_Rails_Deflate assumes the file is actually gzipped. 
4. Heroku_Rails_Deflate, assuming the file is compressed (it isn't), adds Content-Encoding: header that confuses Chrome.

So the problem is that there is no test for whether the file is actually compressed – the test merely examines what Rack::Util thinks is the best encoding, not what is actually in use.

If you take a look at Heroku Deflater (https://github.com/romanbsd/heroku-deflater) you'll see it has a "Skip Binary" feature – essentially whitelisting the types of files that it will compress. This resolves the problem by avoiding it – the files in question aren't in the white list, so the Content-Encoding header is never added.

A more robust way to solve this problem, though, would be to examine the file body itself. Per RFC 1952 (Gzip file specification) the first two bytes of a gzipped file are 1F and 8B, respectively. This can produce false positives, though.

**Comment by mattolson** [comment]
Hi @zetlan -- first of all, sorry for the late reply. I too am experiencing problems with Dragonfly. I am working on the fix and will update the gem shortly.

As for your specific comments: Rack::Utils.select_best_encoding merely tells us which encoding to select based on the client's Accept headers, but doesn't play into determining whether the file is currently compressed.

This gem does two things: (1) enable Rack::Deflate for all requests (2) Serve gzipped versions of static files if they exist on the file system due to asset precompile. #2 works well, #1 has problems depending on the rest of the middleware stack. I am working on the fix.

**Comment by mattolson** [comment]
@zetlan After further review, I found the trouble I was having with Dragonfly related to the use of Rack::Cache and memcache on Heroku. See http://stackoverflow.com/questions/17656999/how-to-cache-files-over-1mb-with-rack-cache-on-heroku for the fix.
