### ISSUE TITLE
rack dependency needs to relax for Rails 4

### ISSUE THREAD

**Issue by nathany** [mattolson/heroku_rails_deflate#13]
actionpack (4.0.2) depends on rack (~> 1.5.2)

so I end up with version heroku_rails_deflate (0.2.0)

**Comment by mattolson** [comment]
OK, I haven't actually tested this code with Rails 4 yet, I'm still using 3.2.16. I'll try it with rack 1.5 and see if there are any issues.

**Comment by nathany** [comment]
Awesome. Thanks!

**Comment by mattolson** [comment]
OK, I've release 1.0.3 with relaxed Rack requirements. Please test it out and let me know if you run into any issues.
