### ISSUE TITLE
Following README setup steps does not lead to production ready setup

### ISSUE THREAD

**Issue by cabe56** [mattolson/heroku_rails_deflate#17]
I followed steps outlined in the README and now see this in my deployed app:
![screen shot 2014-04-17 at 8 43 01 am](https://cloud.githubusercontent.com/assets/822139/2732113/488cdb36-c636-11e3-9c6e-feee93d03303.png)

**Comment by orendon** [comment]
@cabe56 I'm using this with success on heroku.
is this still an issue for you? did you configured `config.serve_static_assets = false`?

**Comment by cabe56** [comment]
@orendon the README says to set it to true, could you elaborate on why you suggest doing otherwise?

**Comment by cabe56** [comment]
Apparently this is properly set up and working in my production app. @orendon thanks for the follow-up.

**Comment by orendon** [comment]
@cabe56 just wanted to check if it wasn't configured properly, glad to hear it's working as expected :+1:
