### ISSUE TITLE
Add dependency

### ISSUE THREAD

**Issue by maletor** [mattolson/heroku_rails_deflate#3]
You should take on https://github.com/romanbsd/heroku-deflater as a dependency.

Otherwise, you'd have to figure out a way to conditionally include Rack::Deflator lest you end up with a stack like this:

```
...
use Rack::Deflater
use HerokuDeflater::SkipBinary
use Rack::Deflater
...
```

**Comment by mattolson** [comment]
This gem and romanbsd/heroku-deflater are mutually exclusive. He has since incorporated most of the code from this gem into his, so if you are inclined to use his version, you should remove mine.
