### ISSUE TITLE
rack/lock.rb in lock ThreadError: deadlock; recursive locking

### ISSUE THREAD

**Issue by nelix** [mattolson/heroku_rails_deflate#4]
ThreadError
deadlock; recursive locking

bundle/ruby/1.9.1/bin/unicorn_rails ? in <main>
 load Gem.bin_path('unicorn', 'unicorn_rails', version)
bundle/ruby/1.9.1/bin/unicorn_rails ? in load
 load Gem.bin_path('unicorn', 'unicorn_rails', version)
bundle/ruby/1.9.1/gems/unicorn-4.6.0/bin/unicorn_rails ? in <top (required)>
 Unicorn::HttpServer.new(app, options).start.join
unicorn/http_server.rb ? in start
     spawn_missing_workers
unicorn/http_server.rb ? in spawn_missing_workers
         worker_loop(worker)
new_relic/agent/instrumentation/unicorn_instrumentation.rb ? in block (4 levels) in <top (required)>
         old_worker_loop.bind(self).call(worker)
new_relic/agent/instrumentation/unicorn_instrumentation.rb ? in call
         old_worker_loop.bind(self).call(worker)
unicorn/http_server.rb ? in worker_loop
           process_client(client)
unicorn/http_server.rb ? in process_client
     status, headers, body = @app.call(env = @request.read(client))
rails/railtie/configurable.rb ? in method_missing
           instance.send(_args, &block)
rails/application.rb ? in call
       super(env)
rails/engine.rb ? in call
       app.call(env.merge!(env_config))
raven/rack.rb ? in call
         response = @app.call(env)
rack/cache/context.rb ? in call
         clone.call! env
rack/cache/context.rb ? in call!
             lookup
rack/cache/context.rb ? in lookup
           fetch
rack/cache/context.rb ? in fetch
       response = forward
rack/cache/context.rb ? in forward
       Response.new(_backend.call(@env))
rack/deflater.rb ? in call
       status, headers, body = @app.call(env)
heroku_rails_deflate/serve_zipped_assets.rb ? in call
       @app.call(env)
action_dispatch/middleware/static.rb ? in call
       @app.call(env)
rack/lock.rb ? in call
       @mutex.lock
rack/lock.rb ? in lock
       @mutex.lock

I think it has something to do with .close in rack middleware.
https://github.com/rack/rack/commit/d2c53f30825c19c0f0c2aadb246c38ffa7c6146e
Can we use this with rack 1.5?

**Comment by mattolson** [comment]
@nelix Sorry for the late reply. I have no idea what's going on here, I haven't seen this before. If it requires an update of rack, it will be difficult to support Rails 3.2, which requires 1.4.5. Do you have a test case I can look at to help narrow this down?

**Comment by xentek** [comment]
I am also seeing this intermittently on one of my apps. I will fork this repo and try a few things and see if I can come up with a patch that fixes it. Still investigating the issue, but essentially it does boil down to closing the body. `Rack::Lock` is throwing the deadlock exception. Another conversation about this error that may prove useful: https://github.com/rack/rack/issues/168

**Comment by xentek** [comment]
Kindly ignore commit 8c6b141bad533d6f44adcad9e18aee99802f75ba. Once I had it working, I made the change on a new branch (see d17080eb2477dadbe5345cd51c0ef4063022f39a) to ensure the pull request was free of debris. 

@nelix if you're in a position to test my patch in your environment, let me know. I know you reported this issue 3 months ago and may have since moved on, but more testing of this change may be warranted before this issue can be declared fixed and closed.

:shipit:

**Comment by mattolson** [comment]
Fixed in 0fe25c49da724424498de4ff5d457cc42aacdbd1 by @xentek
