### ISSUE TITLE
Question: What exactly is the downside of not precompiling assets prior to deployment (Rails 3.2) 

### ISSUE THREAD

**Issue by dommmel** [mattolson/heroku_rails_deflate#5]
Thanks for the gem!

I have a project where I use a lot of ENV-variables in my assets for various reasons. That make precompiling the assets locally a bit messy.

My understanding was that compiling assets during heroku's slug compilation is more or less the same than doing it locally and then pushing them to heroku.

The README mentiones that precompiling helps to "save CPU cycles at request time". Could you explain to me if that is also true for assets compiled during slug compilation?

Thanks a ton

**Comment by alexslade** [comment]
@dommmel I might be wrong, but I think that heroku's slug precompile is the same as doing it locally. I personally hate checking in compiled files, always leaving it to be done on the server.

**Comment by mattolson** [comment]
@dommmel Sorry for the late reply. I precompile assets before deployment mainly to make sure it will succeed without any surprises later. If asset compilation fails during slug creation, Heroku will proceed but then runtime compilation will be enabled, which slows your app down tremendously. So yes, it's a bit of a hassle to do this ahead of time and check them into your repository, but it gives me peace of mind knowing that everything is working ahead of deployment. It also speeds deployment if that is a concern to you. I will update the readme to state that this is optional, it's not entirely relevant to the functioning of this gem.
