### ISSUE TITLE
Installation help

### ISSUE THREAD

**Issue by rahilsondhi** [mattolson/heroku_rails_deflate#6]
Hey guys,

I tried using this gem. I put `gem 'heroku_rails_deflate', group: [:production, :staging]` in my `Gemfile`. When my staging server restarted, in Chrome Dev Tools, I expected JavaScripts to have `Content-Encoding:gzip` under `Response Headers` but it wasn't there. I tried with and without an asset host (I use CloudFront).

Without the gem, if I simply put `use Rack::Deflater` in `config.ru` and **I don't use an asset host**, then the assets served are being gzipped and I see `Content-Encoding:gzip` under `Response Headers`.

I'm hoping this gem will allow me to serve gzipped assets using CloudFront, that's my goal.

**Comment by mattolson** [comment]
Hi @rahilsondhi, sorry for the late reply. If you are using CloudFront, it depends on how your distribution is set up. 

If it is pulling from an S3 bucket, you can use the asset_sync gem, which hooks into your local precompile step and pushes the files to an S3 bucket of your choosing (this is what I do for some apps and it works well). asset_sync is smart enough to look at the compressed version and the uncompressed version and push whichever one it thinks will be fastest (it's a balance of size differential and cpu cycles for decompression) and simply replace the normal version with the compressed one on S3 if that will be faster. It also sets the content type header appropriately so browsers do the right thing.

If it is setup to pull from the origin server, then this gem and your app settings are relevant. As long as you follow the steps in the readme for installation, the Rails app will deliver the asset with the appropriate headers and CloudFront should pass them on.

**Comment by xentek** [comment]
One way to debug this is to look for *.gz files in `public/assets` when you run `RAILS_ENV=production RAILS_GROUPS=assets bundle exec rake assets:precompile:all` on your local machine. (You'll want to `rm -rf public/assets` after you're done inspecting the results)

**Comment by cheeyeo** [comment]
If you are also using Rack::Cache in production make sure it is loaded after both Rack::Deflater and HerokuRailsDeflate::ServeZippedAssets else it will serve the cached non-gzip version if you are serving static assets. Only found this out by accident on a heroku production app
